name: workflow.yml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          enable-cache: 'true'

      - name: Run checks
        run: devbox run check

      - name: Run a script called test
        run: devbox run test
